# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-10-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('loopback', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
